# Arch-KDE Stow 清单

[NO_FOLD]
KDE         # KDE桌面环境
Xremap      # 按键映射
Ydotool     # 按键操控
Rime-Ice    # 雾凇拼音Rime
VSCode      # VSCode编辑器
MyScripts   # 个人脚本

[FOLD]
WezTerm Kitty Ghostty  # 终端
Bash Fish   # Shell
OhMyPosh    # Shell美化
Yazi        # TUI文件浏览
Btop        # TUI资源监控

FontConfig  # 字体配置
Fcitx5      # 输入法框架

Pictures    # 个人图片
Flameshot   # 火焰截图
MPV         # MPV播放器

Mise        # Mise环境管理
Ruff        # Ruff代码风格
LazyVim     # Neovim配置
Jetbrains   # JetBrains配置
