[open]
append_rules = [{ name = "*/", use = ["open", "edit"], for = "windows" }]

[opener]
edit = [{ desc = "NeoVim", for = "windows", block = true, run = 'nvim %*' }]
play = [{ desc = "PotPlayer", for = "windows", orphan = true, run = '"C:/Program Files/DAUM/PotPlayer/PotPlayerMini64.exe" %0' }]
open = [
    { desc = "Open", for = "windows", orphan = true, run = 'start "" "%1"' },
    { desc = "VSCode", for = "windows", orphan = true, run = 'code %*' },
    { desc = "PotPlayer", for = "windows", orphan = true, run = '"C:/Program Files/DAUM/PotPlayer/PotPlayerMini64.exe" %0' },
]

[plugin]
prepend_previewers = [{ mime = "video/*", run = "noop" }]