LANG=en_US.UTF-8
LC_MESSAGES=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US

EDITOR=nvim
VISUAL=nvim

XMODIFIERS=@im=fcitx

XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_STATE_HOME=$HOME/.local/state
XDG_CACHE_HOME=$HOME/.cache
XDG_BIN_HOME=$HOME/.local/bin