[tools]
aube      = "latest" # aube自动代替npm作为包管理器, 用 mise use -g 代替 npm install -g
usage     = "latest"
pitchfork = "latest"
gh        = "latest"

# Windows 的 PI 需要在 ~/.pi/agent/settings.json 配置 Shell 路径
# 选择建议: pwsh 执行命令兼容性更好 ; bash 命令更实用, 但执行某些 Windows 程序(比如 winget)命令可能有 bug
#   bash配置:
#       "shellPath": "C:/msys64/usr/bin/bash.exe"
#   pwsh配置(额外设置 UTF8 编码防止乱码):
#       "shellPath": "C:/Program Files/PowerShell/7/pwsh.exe"
#       "shellCommandPrefix": "[Console]::OutputEncoding = [Text.Encoding]::UTF8; "
pi     = "latest"
claude = "latest"
"npm:skills" = "latest"

rust   = "stable"
node   = "lts"
uv     = "latest"
ruff   = "latest"
stylua = "latest"
oxfmt  = "latest"
oxlint = "latest"

[settings]
minimum_release_age = "24h" # s=秒 m=分 h=时 d=天 w=周 mo=月 y=年, "0s"禁用
minimum_release_age_excludes = ["pi", "claude"]
rust.default_host = "x86_64-pc-windows-gnu" # 默认编译目标设为 GNU, 省去安装 Visual Studio Build Tools
idiomatic_version_file_enable_tools = ["java", "node", "pnpm", "rust"]

# 有时候 mise upgrade 可能没清理掉旧版本工具, 可执行 mise prune 手动清理
