[tools]
# Langs
java  = "25"
maven = "3"
node  = "lts"

# CLI utilities
usage = "latest" # Mise命令补全
pnpm  = "latest"
uv    = "latest"
ruff  = "latest"

# AI CLI tools
claude   = "latest"
codex    = "latest"
opencode = "latest"
"npm:snow-ai"             = "latest"
"npm:@iflow-ai/iflow-cli" = "latest"

[settings]
npm.package_manager = "pnpm" # 使用 pnpm 作为 npm 包的下载器. 别用 pnpm install -g , 用 mise use -g
idiomatic_version_file_enable_tools = ["python", "node", "pnpm", "java"]
