[tools]
aube      = "latest" # aube自动代替npm作为包管理器, 用 mise use -g 代替 npm install -g
usage     = "latest"
pitchfork = "latest"
gh        = "latest"

pi       = "latest"
claude   = "latest"
"npm:skills" = "latest"
"github:can1357/oh-my-pi" = "latest"

rust = "stable"
cargo-binstall = "latest"

java   = "25"
maven  = "3"
node   = "lts"
uv     = "latest"
ruff   = "latest"
stylua = "latest"
oxfmt  = "latest"
oxlint = "latest"

[settings]
minimum_release_age = "24h" # s=秒 m=分 h=时 d=天 w=周 mo=月 y=年, "0s"禁用
minimum_release_age_excludes = ["pi", "claude", "github:can1357/oh-my-pi"]
idiomatic_version_file_enable_tools = ["java", "node", "pnpm", "rust"]

# 有时候 mise upgrade 可能没清理掉旧版本工具, 可执行 mise prune 手动清理
