[tools]
aube      = "latest" # aube自动代替npm作为包管理器, 用 mise use -g 代替 npm install -g
usage     = "latest"
pitchfork = "latest"
gh        = "latest"

pi     = "latest"
"npm:skills" = "latest"

node   = "lts"
uv     = "latest"
ruff   = "latest"
stylua = "latest"
oxfmt  = "latest"
oxlint = "latest"

[settings]
minimum_release_age = "24h"
minimum_release_age_excludes = ["pi", "claude"]
idiomatic_version_file_enable_tools = ["java", "node", "pnpm", "rust"]
