# ===== 清空原有快捷键 =====
keybind = clear
# ===== 重载配置 =====
keybind = ctrl+shift+,=reload_config
# ===== 命令面板 =====
keybind = ctrl+shift+p=toggle_command_palette
# ===== 搜索 =====
keybind = ctrl+shift+f=start_search
keybind = escape=end_search
# ===== 选择 =====
keybind = ctrl+shift+a=select_all
keybind = shift+arrow_left=adjust_selection:left
keybind = shift+arrow_right=adjust_selection:right
keybind = shift+arrow_up=adjust_selection:up
keybind = shift+arrow_down=adjust_selection:down
# 注:按住 Ctrl + Alt 鼠标可矩形选中
# ===== 复制粘贴 =====
keybind = copy=copy_to_clipboard:mixed
keybind = ctrl+shift+c=copy_to_clipboard:mixed
keybind = ctrl+insert=copy_to_clipboard:mixed
keybind = paste=paste_from_clipboard
keybind = ctrl+shift+v=paste_from_clipboard
keybind = shift+insert=paste_from_selection
# ===== 滚动 =====
keybind = ctrl+shift+y=scroll_page_lines:-3
keybind = ctrl+shift+e=scroll_page_lines:3
keybind = ctrl+shift+u=jump_to_prompt:-1
keybind = ctrl+shift+d=jump_to_prompt:1
keybind = ctrl+shift+page_up=scroll_page_up
keybind = ctrl+shift+page_down=scroll_page_down
keybind = ctrl+shift+home=scroll_to_top
keybind = ctrl+shift+end=scroll_to_bottom
keybind = ctrl+shift+alt+home=clear_screen
# ===== 窗口管理 =====
keybind = alt+f4=close_window
keybind = ctrl+shift+f11=toggle_fullscreen
# ===== 标签页管理 =====
keybind = ctrl+shift+t=new_tab
keybind = ctrl+tab=next_tab
keybind = ctrl+shift+tab=previous_tab
keybind = ctrl+shift+alt+t=prompt_tab_title
keybind = ctrl+shift+alt+w=close_tab
# 标签页按数字切换
keybind = ctrl+alt+1=goto_tab:1
keybind = ctrl+alt+2=goto_tab:2
keybind = ctrl+alt+3=goto_tab:3
keybind = ctrl+alt+4=goto_tab:4
keybind = ctrl+alt+5=goto_tab:5
keybind = ctrl+alt+6=goto_tab:6
keybind = ctrl+alt+7=goto_tab:7
keybind = ctrl+alt+8=goto_tab:8
keybind = ctrl+alt+9=goto_tab:9
# ===== 分屏管理 =====
# 关闭分屏
keybind = ctrl+shift+w=close_surface
# 分屏
keybind = ctrl+shift+alt+enter=new_split:down
keybind = ctrl+shift+enter=new_split:right
# 分屏导航
keybind = ctrl+shift+h=goto_split:left
keybind = ctrl+shift+j=goto_split:down
keybind = ctrl+shift+k=goto_split:up
keybind = ctrl+shift+l=goto_split:right
keybind = ctrl+shift+[=goto_split:previous
keybind = ctrl+shift+]=goto_split:next
# 分屏大小调整
keybind = ctrl+shift+left=resize_split:left,10
keybind = ctrl+shift+right=resize_split:right,10
keybind = ctrl+shift+up=resize_split:up,10
keybind = ctrl+shift+down=resize_split:down,10
keybind = ctrl+shift+z=toggle_split_zoom
keybind = ctrl+shift+|=equalize_splits
# ===== 字体大小 =====
keybind = ctrl+0=reset_font_size
keybind = ctrl+-=decrease_font_size:1
keybind = ctrl+shift++=increase_font_size:1
