clear_all_shortcuts yes
kitty_mod ctrl+shift
enabled_layouts splits
# ===== 命令面板 =====
map kitty_mod+p command_palette
# ===== 搜索 =====
map kitty_mod+f search_scrollback
# ===== 选择 / 复制 =====
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+x show_scrollback
map kitty_mod+space kitten hints --type=url --program @
# ===== 滚动 =====
map kitty_mod+y scroll_line_up
map kitty_mod+e scroll_line_down
map kitty_mod+u scroll_to_prompt -1
map kitty_mod+d scroll_to_prompt 1
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home scroll_home
map kitty_mod+end scroll_end
map kitty_mod+alt+home clear_terminal scrollback
# ===== 窗口管理 =====
map kitty_mod+f11 toggle_fullscreen
# ===== Tabs（标签页） =====
map kitty_mod+t new_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+shift+alt+w close_tab
map ctrl+shift+alt+t set_tab_title
map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 9
# ===== Pane（分屏） =====
map ctrl+shift+alt+enter launch --location=hsplit
map ctrl+shift+enter launch --location=vsplit
map kitty_mod+w close_window
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right
map kitty_mod+left resize_window narrower
map kitty_mod+right resize_window wider
map kitty_mod+up resize_window taller
map kitty_mod+down resize_window shorter
# ===== 字体大小 =====
map ctrl+0 change_font_size all 0
map ctrl+minus change_font_size all -2.0
map ctrl+shift+equal change_font_size all +2.0
